// Code generated by github.com/swaggest/json-cli v1.8.3, DO NOT EDIT.

// Package transaction contains JSON mapping structures.
package transaction

import (
	"github.com/google/uuid"
)

// Transaction structure is generated from "openapi.yaml#/components/schemas/Transaction".
type Transaction struct {
	// Format: uuid.
	// Required.
	ID uuid.UUID `json:"id"`
	// Format: uuid.
	// Required.
	UserID               uuid.UUID `json:"userId"`
	Type                 string    `json:"type"`         // Required.
	Amount               float64   `json:"amount"`       // Required.
	CurrencyCode         string    `json:"currencyCode"` // Required.
	OriginalAmount       float64   `json:"originalAmount,omitempty"`
	OriginalCurrency     string    `json:"originalCurrency,omitempty"`
	ExchangeRate         float64   `json:"exchangeRate,omitempty"`
	MerchantCity         string    `json:"merchantCity,omitempty"`
	VisibleTS            int64     `json:"visibleTS"` // Required.
	Mcc                  int64     `json:"mcc,omitempty"`
	MccGroup             int64     `json:"mccGroup,omitempty"`
	MerchantName         string    `json:"merchantName,omitempty"`
	Recurring            bool      `json:"recurring,omitempty"`
	PartnerBankName      string    `json:"partnerBankName,omitempty"`
	PartnerBic           string    `json:"partnerBic,omitempty"`
	PartnerBcn           string    `json:"partnerBcn,omitempty"`
	PartnerAccountIsSepa bool      `json:"partnerAccountIsSepa,omitempty"`
	PartnerName          string    `json:"partnerName,omitempty"`
	// Format: uuid.
	// Required.
	AccountID           uuid.UUID `json:"accountId"`
	PartnerIban         string    `json:"partnerIban,omitempty"`
	PartnerAccountBan   string    `json:"partnerAccountBan,omitempty"`
	Category            string    `json:"category"`         // Required.
	CardID              uuid.UUID `json:"cardId,omitempty"` // Format: uuid.
	ReferenceText       string    `json:"referenceText,omitempty"`
	UserAccepted        int64     `json:"userAccepted,omitempty"`
	UserCertified       int64     `json:"userCertified"`     // Required.
	Pending             bool      `json:"pending"`           // Required.
	Nature              string    `json:"transactionNature"` // Required.
	CreatedTS           int64     `json:"createdTS"`         // Required.
	MerchantCountry     int64     `json:"merchantCountry,omitempty"`
	MerchantCountryCode int64     `json:"merchantCountryCode,omitempty"`
	// Format: uuid.
	// Required.
	SmartLinkID    uuid.UUID `json:"smartLinkId"`
	SmartContactID uuid.UUID `json:"smartContactId,omitempty"` // Format: uuid.
	// Format: uuid.
	// Required.
	LinkID       uuid.UUID `json:"linkId"`
	TxnCondition string    `json:"txnCondition,omitempty"`
	Confirmed    int64     `json:"confirmed"` // Required.
}
