// Code generated by github.com/swaggest/swac v0.1.19, DO NOT EDIT.

package api

import (
	"time"
)

// TokenResponse structure is generated from "#/components/schemas/TokenResponse".
type TokenResponse struct {
	AccessToken  string `json:"access_token"` // Required.
	TokenType    string `json:"token_type,omitempty"`
	RefreshToken string `json:"refresh_token"` // Required.
	ExpiresIn    int64  `json:"expires_in"`    // Required.
	HostURL      string `json:"host_url,omitempty"`
}

// BadCredentialsError structure is generated from "#/components/schemas/BadCredentialsError".
type BadCredentialsError struct {
	Status           int64       `json:"status,omitempty"`
	Detail           string      `json:"detail,omitempty"`
	Type             string      `json:"type,omitempty"`
	UserMessage      UserMessage `json:"userMessage"` // Required.
	Error            string      `json:"error,omitempty"`
	ErrorDescription string      `json:"error_description,omitempty"`
}

// UserMessage structure is generated from "#/components/schemas/UserMessage".
type UserMessage struct {
	Title  string `json:"title,omitempty"`
	Detail string `json:"detail,omitempty"`
}

// UnauthorizedAuthError structure is generated from "#/components/schemas/UnauthorizedAuthError".
type UnauthorizedAuthError struct {
	Status           int64       `json:"status,omitempty"`
	Detail           string      `json:"detail,omitempty"`
	Type             string      `json:"type,omitempty"`
	UserMessage      UserMessage `json:"userMessage"` // Required.
	Error            string      `json:"error,omitempty"`
	ErrorDescription string      `json:"error_description,omitempty"`
}

// RequiredMFATokenError structure is generated from "#/components/schemas/RequiredMFATokenError".
type RequiredMFATokenError struct {
	UserMessage UserMessage `json:"userMessage"` // Required.
	// Format: uuid.
	// Required.
	MfaToken         string `json:"mfaToken"`
	ErrorDescription string `json:"error_description,omitempty"`
	Detail           string `json:"detail,omitempty"`
	HostURL          string `json:"hostUrl,omitempty"`
	Type             string `json:"type,omitempty"`
	Error            string `json:"error,omitempty"`
	Title            string `json:"title,omitempty"`
	Message          string `json:"message,omitempty"`
	// Format: uuid.
	// Required.
	UserID string `json:"userId"`
	Status int64  `json:"status,omitempty"`
}

// TooManyLoginAttemptsError structure is generated from "#/components/schemas/TooManyLoginAttemptsError".
type TooManyLoginAttemptsError struct {
	Status      int64       `json:"status,omitempty"`
	Detail      string      `json:"detail,omitempty"`
	UserMessage UserMessage `json:"userMessage"` // Required.
	Error       string      `json:"error,omitempty"`
	Title       string      `json:"title,omitempty"`
	Message     string      `json:"message,omitempty"`
}

// MFAChallengeRequest structure is generated from "#/components/schemas/MFAChallengeRequest".
type MFAChallengeRequest struct {
	ChallengeType string `json:"challengeType"` // Required.
	MfaToken      string `json:"mfaToken"`      // Required.
}

// PostAPIMfaChallengeResponseValueCreated structure is generated from "PostAPIMfaChallenge/response/ValueCreated".
type PostAPIMfaChallengeResponseValueCreated struct {
	ChallengeType string `json:"challengeType,omitempty"`
}

// UnauthorizedMfaChallengeError structure is generated from "#/components/schemas/UnauthorizedMfaChallengeError".
type UnauthorizedMfaChallengeError struct {
	Timestamp *time.Time `json:"timestamp,omitempty"` // Format: date-time.
	Status    int64      `json:"status,omitempty"`
	Error     string     `json:"error,omitempty"`
	Message   string     `json:"message,omitempty"`
	Path      string     `json:"path,omitempty"`
}

// InvalidTokenError structure is generated from "#/components/schemas/InvalidTokenError".
type InvalidTokenError struct {
	Status           int64       `json:"status,omitempty"`
	Detail           string      `json:"detail,omitempty"`
	Type             string      `json:"type,omitempty"`
	UserMessage      UserMessage `json:"userMessage"` // Required.
	Error            string      `json:"error,omitempty"`
	ErrorDescription string      `json:"error_description,omitempty"`
}
