// Code generated by github.com/swaggest/swac v0.1.19, DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"io/ioutil"
	"net/http"
)

// PostAPIMfaChallengeRequest is operation request value.
type PostAPIMfaChallengeRequest struct {
	DeviceToken string               // DeviceToken is a required `device-token` parameter in header.
	Body        *MFAChallengeRequest // Body is a JSON request body.
}

// encode creates *http.Request for request data.
func (request *PostAPIMfaChallengeRequest) encode(ctx context.Context, baseURL string) (*http.Request, error) {
	requestURI := baseURL + "/api/mfa/challenge"

	body, err := json.Marshal(request.Body)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, requestURI, bytes.NewBuffer(body))
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", "application/json; charset=utf-8")
	req.Header.Set("Accept", "application/json")

	req.Header.Set("device-token", request.DeviceToken)

	req = req.WithContext(ctx)

	return req, err
}

// PostAPIMfaChallengeResponse is operation response value.
type PostAPIMfaChallengeResponse struct {
	StatusCode        int
	ValueCreated      *PostAPIMfaChallengeResponseValueCreated // ValueCreated is a value of 201 Created response.
	ValueBadRequest   *BadCredentialsError                     // ValueBadRequest is a value of 400 Bad Request response.
	ValueUnauthorized *UnauthorizedMfaChallengeError           // ValueUnauthorized is a value of 401 Unauthorized response.
}

// decode loads data from *http.Response.
func (result *PostAPIMfaChallengeResponse) decode(resp *http.Response) error {
	var err error

	dump := bytes.NewBuffer(nil)
	body := io.TeeReader(resp.Body, dump)

	result.StatusCode = resp.StatusCode

	switch resp.StatusCode {
	case http.StatusCreated:
		err = json.NewDecoder(body).Decode(&result.ValueCreated)
	case http.StatusBadRequest:
		err = json.NewDecoder(body).Decode(&result.ValueBadRequest)
	case http.StatusUnauthorized:
		err = json.NewDecoder(body).Decode(&result.ValueUnauthorized)
	default:
		_, readErr := ioutil.ReadAll(body)
		if readErr != nil {
			err = errors.New("unexpected response status: " + resp.Status +
				", could not read response body: " + readErr.Error())
		} else {
			err = errors.New("unexpected response status: " + resp.Status)
		}
	}

	if err != nil {
		return responseError{
			resp: resp,
			body: dump.Bytes(),
			err:  err,
		}
	}

	return nil
}

// PostAPIMfaChallenge performs REST operation.
func (c *Client) PostAPIMfaChallenge(ctx context.Context, request PostAPIMfaChallengeRequest) (result PostAPIMfaChallengeResponse, err error) {
	if c.InstrumentCtxFunc != nil {
		ctx = c.InstrumentCtxFunc(ctx, http.MethodPost, "/api/mfa/challenge", &request)
	}

	if c.Timeout != 0 {
		var cancel func()
		ctx, cancel = context.WithTimeout(ctx, c.Timeout)

		defer cancel()
	}

	req, err := request.encode(ctx, c.BaseURL)
	if err != nil {
		return result, err
	}

	resp, err := c.transport.RoundTrip(req)

	if err != nil {
		return result, err
	}

	defer func() {
		closeErr := resp.Body.Close()
		if closeErr != nil && err == nil {
			err = closeErr
		}
	}()

	err = result.decode(resp)

	return result, err
}
